import type { AnalysisResult, StackInfo, DependencyGroup } from '../models/index.js';

function stackBadge(stack: StackInfo): string {
  const label = encodeURIComponent(stack.displayName.replace(/-/g, '--'));
  const color = stack.confidence === 'high' ? 'blue' : stack.confidence === 'medium' ? 'yellow' : 'lightgrey';
  return `![${stack.displayName}](https://img.shields.io/badge/${label}-${color}?style=flat-square)`;
}

function depTable(group: DependencyGroup): string {
  const rows = group.runtime
    .slice(0, 15)
    .map((d) => `| \`${d.name}\` | \`${d.version}\` | Runtime |`)
    .concat(group.dev.slice(0, 8).map((d) => `| \`${d.name}\` | \`${d.version}\` | Dev |`));

  if (rows.length === 0) return '';

  return [
    `### \`${group.source}\``,
    '',
    '| Package | Version | Type |',
    '|---------|---------|------|',
    ...rows,
  ].join('\n');
}

export function formatMarkdown(result: AnalysisResult): string {
  const { projectInfo, detectedStacks, structure, dependencyGroups, architectureSummary, diagram, metadata } =
    result;

  const lines: string[] = [];

  lines.push(`# RepoLens Report: ${projectInfo.repoName}`);
  lines.push('');
  lines.push(`> Generated by [RepoLens](https://github.com/repolens/repolens) on ${new Date(metadata.analyzedAt).toUTCString()}`);
  lines.push('');

  if (detectedStacks.length > 0) {
    lines.push(detectedStacks.map(stackBadge).join(' '));
    lines.push('');
  }

  lines.push('## Architecture Summary');
  lines.push('');
  lines.push(architectureSummary || '_No summary available._');
  lines.push('');

  lines.push('## Detected Stacks');
  lines.push('');
  lines.push('| Technology | Version | Confidence | Evidence |');
  lines.push('|-----------|---------|------------|---------|');
  for (const stack of detectedStacks) {
    const version = stack.version ?? '—';
    const evidence = stack.evidence.join(', ');
    lines.push(`| **${stack.displayName}** | \`${version}\` | ${stack.confidence} | ${evidence} |`);
  }
  lines.push('');

  lines.push('## Project Structure');
  lines.push('');

  if (structure.entryPoints.length > 0) {
    lines.push('**Entry Points:**');
    lines.push('');
    structure.entryPoints.forEach((ep) => lines.push(`- \`${ep}\``));
    lines.push('');
  }

  if (structure.majorFolders.length > 0) {
    lines.push('**Folder Layout:**');
    lines.push('');
    lines.push('```');
    structure.majorFolders.slice(0, 12).forEach((folder, i) => {
      const isLast = i === structure.majorFolders.length - 1 || i === 11;
      lines.push(`${isLast ? '└──' : '├──'} ${folder}/`);
    });
    lines.push('```');
    lines.push('');
  }

  if (structure.testDirs.length > 0) {
    lines.push('**Test Directories:**');
    lines.push('');
    structure.testDirs.forEach((d) => lines.push(`- \`${d}/\``));
    lines.push('');
  }

  if (structure.configFiles.length > 0) {
    lines.push('**Configuration Files:**');
    lines.push('');
    structure.configFiles.slice(0, 10).forEach((f) => lines.push(`- \`${f}\``));
    lines.push('');
  }

  if (dependencyGroups.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    for (const group of dependencyGroups) {
      lines.push(depTable(group));
      lines.push('');
    }
  }

  if (diagram) {
    lines.push('## Architecture Diagram');
    lines.push('');
    lines.push('```');
    lines.push(diagram);
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `_Analyzed ${structure.totalFiles} files in ${metadata.durationMs}ms · repolens v${metadata.repolensVersion}_`,
  );

  return lines.join('\n');
}
